# ==========================================
# Application
# ==========================================
spring.application.name=Hospital_Management_System
server.port=9091

# ==========================================
# PostgreSQL (Supabase)
# ==========================================
# spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
# spring.datasource.username=postgres.llgpqdjdoaioodqscomh
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# Hikari Connection Pool
# ==========================================
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ==========================================
# File Upload
# ==========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==========================================
# Gmail SMTP
## ==========================================
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.protocol=smtp
#spring.mail.username=hospitalmanagementsystem.com@gmail.com
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000
#spring.mail.properties.mail.smtp.auth.mechanisms=XOAUTH2

# ==========================================
# Google OAuth2
# ==========================================
google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth.refresh-token=${GOOGLE_REFRESH_TOKEN}
google.redirect.uri=https://hospital-management-system-8s44.onrender.com/gmail/callback
google.oauth.access-token=${GOOGLE_ACCESS_TOKEN}
google.oauth.email=${GOOGLE_EMAIL}
google.oauth.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
google.oauth.token-uri=https://oauth2.googleapis.com/token
google.oauth.scope=https://www.googleapis.com/auth/gmail.send
google.oauth.access-type=offline
google.oauth.prompt=consent



# ==========================================
# Supabase Storage
# ==========================================
supabase.url=https://llgpqdjdoaioodqscomh.supabase.co
supabase.bucket=library-management-system
supabase.service.key=YOUR_SUPABASE_SERVICE_KEY