spring.application.name=Hospital_Management_System
DB_URL=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres
DB_USERNAME=postgres.llgpqdjdoaioodqscomh
DB_PASSWORD=Rahul@143#1
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=${PORT:9090}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
SUPABASE_URL=https://llgpqdjdoaioodqscomh.supabase.co
SUPABASE_BUCKET=library-management-system
supabase.url=${SUPABASE_URL}
supabase.bucket=${SUPABASE_BUCKET}
supabase.service.key=${SUPABASE_SERVICE_KEY}